ALTER TABLE profiles ADD COLUMN email TEXT;

ALTER TABLE rsvps ADD COLUMN booker_email TEXT NOT NULL DEFAULT '';
ALTER TABLE rsvps ALTER COLUMN booker_email DROP DEFAULT;
ALTER TABLE rsvps ADD COLUMN status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE rsvps ADD COLUMN deny_reason TEXT;
